[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
json = "0.12.4"
rocket = { version = "0.5.1", features = ["json"] }
rocket_dyn_templates = { version = "0.1.0", features = ["handlebars"] }
serde = { version = "1.0.206", features = ["derive"] }
serde_json = "1.0.124"
